ALTER TYPE statut_rdv_enum ADD VALUE IF NOT EXISTS 'EN_COURS';
ALTER TABLE rdv ADD COLUMN IF NOT EXISTS date_debut_reelle TIMESTAMPTZ;
ALTER TABLE rdv ADD COLUMN IF NOT EXISTS date_pause TIMESTAMPTZ;
ALTER TABLE rdv ADD COLUMN IF NOT EXISTS duree_pause_secondes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE rdv ADD COLUMN IF NOT EXISTS date_fin_reelle TIMESTAMPTZ;
ALTER TABLE fiche_technique ADD COLUMN IF NOT EXISTS type_cheveu VARCHAR(30);
ALTER TABLE fiche_technique ADD COLUMN IF NOT EXISTS sensibilites TEXT;
ALTER TABLE fiche_technique ADD COLUMN IF NOT EXISTS produits_utilises TEXT;
ALTER TABLE fiche_technique ADD COLUMN IF NOT EXISTS boisson_preferee VARCHAR(80);