ALTER TABLE avis ADD COLUMN IF NOT EXISTS url_photo_avant TEXT;
ALTER TABLE avis ADD COLUMN IF NOT EXISTS url_photo_apres TEXT;ALTER TABLE avis ADD COLUMN IF NOT EXISTS photos_partage_public BOOLEAN NOT NULL DEFAULT false;
