using Dapper;
using KekeBeauty.Application.Admin;
namespace KekeBeauty.Infrastructure.Admin;
public sealed class AdminManagementRepository(IDbConnectionFactory factory):IAdminManagementRepository {
 public async Task<AdminAccount?> FindByEmailAsync(string email,CancellationToken ct){using var c=factory.CreateConnection();await c.OpenAsync(ct);return await c.QuerySingleOrDefaultAsync<AdminAccount>(new CommandDefinition(@"SELECT id_admin IdAdmin,nom,email,mot_de_passe_hash MotDePasseHash,role,actif FROM compte_admin WHERE lower(email)=lower(@email)",new{email},cancellationToken:ct));}
 public async Task<AdminAccount?> FindByIdAsync(Guid id,CancellationToken ct){using var c=factory.CreateConnection();await c.OpenAsync(ct);return await c.QuerySingleOrDefaultAsync<AdminAccount>(new CommandDefinition(@"SELECT id_admin IdAdmin,nom,email,mot_de_passe_hash MotDePasseHash,role,actif FROM compte_admin WHERE id_admin=@id",new{id},cancellationToken:ct));}
 public async Task<int> CountAdminsAsync(CancellationToken ct){using var c=factory.CreateConnection();await c.OpenAsync(ct);return await c.ExecuteScalarAsync<int>(new CommandDefinition("SELECT count(*) FROM compte_admin",cancellationToken:ct));}
 public async Task<Guid> CreateAdminAsync(string nom,string email,string passwordHash,string role,CancellationToken ct){using var c=factory.CreateConnection();await c.OpenAsync(ct);return await c.ExecuteScalarAsync<Guid>(new CommandDefinition(@"INSERT INTO compte_admin(nom,email,mot_de_passe_hash,role) VALUES(@nom,lower(@email),@passwordHash,@role) RETURNING id_admin",new{nom,email,passwordHash,role},cancellationToken:ct));}
 public async Task TouchLoginAsync(Guid id,CancellationToken ct){using var c=factory.CreateConnection();await c.OpenAsync(ct);await c.ExecuteAsync(new CommandDefinition("UPDATE compte_admin SET derniere_connexion=now() WHERE id_admin=@id",new{id},cancellationToken:ct));}
 public async Task<IReadOnlyList<AdminUserItem>> SearchUsersAsync(string? q,CancellationToken ct){using var c=factory.CreateConnection();await c.OpenAsync(ct);var s=$"%{q?.Trim()??""}%";var x=await c.QueryAsync<AdminUserItem>(new CommandDefinition(@"SELECT id_utilisateur IdUtilisateur,nom,telephone,email,type_compte::text TypeCompte,est_suspendu EstSuspendu,date_creation DateCreation FROM utilisateur WHERE @q='%%' OR nom ILIKE @q OR telephone ILIKE @q OR COALESCE(email,'') ILIKE @q ORDER BY date_creation DESC LIMIT 200",new{q=s},cancellationToken:ct));return x.AsList();}
 public async Task<IReadOnlyList<AdminShopItem>> SearchShopsAsync(string? q,CancellationToken ct){using var c=factory.CreateConnection();await c.OpenAsync(ct);var s=$"%{q?.Trim()??""}%";var x=await c.QueryAsync<AdminShopItem>(new CommandDefinition(@"SELECT e.id_etablissement IdEtablissement,e.nom_etablissement NomEtablissement,u.nom Gerant,e.numero_service_client Telephone,e.statut_kyc::text StatutKyc,e.est_suspendu EstSuspendu,e.date_creation DateCreation FROM etablissement e JOIN utilisateur u ON u.id_utilisateur=e.id_utilisateur_gerant WHERE @q='%%' OR e.nom_etablissement ILIKE @q OR u.nom ILIKE @q OR e.numero_service_client ILIKE @q ORDER BY e.date_creation DESC LIMIT 200",new{q=s},cancellationToken:ct));return x.AsList();}
 public async Task AuditAsync(Guid? adminId,string adminName,string action,string? targetType,Guid? targetId,string? details,string? ip,CancellationToken ct){using var c=factory.CreateConnection();await c.OpenAsync(ct);await c.ExecuteAsync(new CommandDefinition(@"INSERT INTO journal_admin(id_admin,nom_admin,action,type_cible,id_cible,details,adresse_ip) VALUES(@adminId,@adminName,@action,@targetType,@targetId,@details,@ip)",new{adminId,adminName,action,targetType,targetId,details,ip},cancellationToken:ct));}
 public async Task<IReadOnlyList<AdminAuditItem>> ListAuditAsync(CancellationToken ct){using var c=factory.CreateConnection();await c.OpenAsync(ct);var x=await c.QueryAsync<AdminAuditItem>(new CommandDefinition(@"SELECT id_journal IdJournal,nom_admin NomAdmin,action,type_cible TypeCible,id_cible IdCible,details,date_action DateAction FROM journal_admin ORDER BY date_action DESC LIMIT 500",cancellationToken:ct));return x.AsList();}
 public async Task<IReadOnlyList<AdminAccountItem>> ListAdminsAsync(CancellationToken ct){using var c=factory.CreateConnection();await c.OpenAsync(ct);var x=await c.QueryAsync<AdminAccountItem>(new CommandDefinition(@"SELECT id_admin IdAdmin,nom,email,role,actif,date_creation DateCreation,derniere_connexion DerniereConnexion FROM compte_admin ORDER BY date_creation",cancellationToken:ct));return x.AsList();}
 public async Task<bool> SetAdminActiveAsync(Guid id,bool active,CancellationToken ct){using var c=factory.CreateConnection();await c.OpenAsync(ct);return await c.ExecuteAsync(new CommandDefinition("UPDATE compte_admin SET actif=@active WHERE id_admin=@id",new{id,active},cancellationToken:ct))>0;}
 public async Task<bool> UpdateAdminPasswordAsync(Guid id,string passwordHash,CancellationToken ct){using var c=factory.CreateConnection();await c.OpenAsync(ct);return await c.ExecuteAsync(new CommandDefinition("UPDATE compte_admin SET mot_de_passe_hash=@passwordHash WHERE id_admin=@id",new{id,passwordHash},cancellationToken:ct))>0;}
}
